//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_BBM_CampaignPromo.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTHUCTAP : DbContext
    {
        public DBTHUCTAP()
            : base("name=DBTHUCTAP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_BBM_SMART_HRM> tbl_BBM_SMART_HRM { get; set; }
        public virtual DbSet<tbl_Bill> tbl_Bill { get; set; }
        public virtual DbSet<tbl_moTaCongViec> tbl_moTaCongViec { get; set; }
        public virtual DbSet<tbl_potong> tbl_potong { get; set; }
        public virtual DbSet<tbl_tmp> tbl_tmp { get; set; }
    }
}
